### ISSUE TITLE
Sample code for the HSN

### ISSUE THREAD

**Issue by MHasanlou1** [IbrahimYang/Hybrid-neural-networks#1]
Could you please provide a helpful and comprehending example of HSN? 
Thanks

**Comment by wzhCUMT** [comment]
Yes, could U please share the HSN code. Thanks@IbrahimYang

**Comment by IbrahimYang** [comment]
Of course, we will update it soon. Thanks for your questions.

**Comment by SoyeonUm** [comment]
@IbrahimYang 
I am very impressed with your research. Thanks for providing the code. 
But like other people, I want to get the HSN code.
When can you provide "Multi-pathway HSN for high-speed vision perception" code in your paper? 
Could you please provide a trained model?
Thanks.

**Comment by IbrahimYang** [comment]
Thank you for your interest in our research
I'm sorry for the delay.
I haven't provided the code yet because I'm struggling with my Ph.D. thesis. DDL is coming soon.
I will try my best and sort the code out at the end of next week. Also, I will provide the code of HSN with a trained model. Don't worry.

**Comment by IbrahimYang** [comment]
> Could you please provide a helpful and comprehending example of HSN? Thanks

We have already released the code of HSN. Thank you for your interest in our research.

**Comment by IbrahimYang** [comment]
> Yes, could U please share the HSN code. Thanks@IbrahimYang

We have already released the code of HSN. Thank you for your interest in our research.

**Comment by IbrahimYang** [comment]
> @IbrahimYang I am very impressed with your research. Thanks for providing the code. But like other people, I want to get the HSN code. When can you provide "Multi-pathway HSN for high-speed vision perception" code in your paper? Could you please provide a trained model? Thanks.

We have already released the code of HSN. The training code and pre-trained model are also available. Thank you for your interest in our research.
