### ISSUE TITLE
I‘m trying to learn how the code running. Can you help me?

### ISSUE THREAD

**Issue by ZhyGao** [IbrahimYang/Hybrid-neural-networks#4]
That's a very interesting project. I'm trying to learn the code for HSN. There are two simple questions here. Wishing for your explanations. 1. I try to train the network as your guidance, but the loss value always keeps about -400 without any decline. When I test the model using the trained model, it looks well. Why? 2. What do the cm and kernel mean in the code? I am not very sure now. Thanks again for your nice project.

**Comment by ZhyGao** [comment]
Another question. 3. When trans the avs_loc or aps_loc to gt_loc, I'm not clear with the formulate, especially "*8". Why 8?

**Comment by Developer-KS** [comment]
Sorry for the late response.

1. I am not able to replicate your issue of loss not declining without more details. The training works well in my setup.
2. cm stands for correlation map and kernel is a 3*3 clip extracted from the feature map generated by passing the APS image through a ANN Resnet. The kernel is extracted at the object location, so it stands for the feature of the target. The cm is generated by convolving the feature map of DVS frame (generated by a SNN Resnet) with the kernel and the location where the correlation is the highest should be the place where the tracked object is.
3. The dvs_loc that is passed into the forward function of TurningDiskSiamFC model is the target location on the DVS feature map. The ground-truth location of the target on the image can be converted from this dvs_loc by a shifting and scaling (by the stride of the SNN Resnet, which is "8").

I hope this solved your problems. Glad to response to any furture questions.

**Comment by SqLiu67** [comment]
> That's a very interesting project. I'm trying to learn the code for HSN. There are two simple questions here. Wishing for your explanations. 1. I try to train the network as your guidance, but the loss value always keeps about -400 without any decline. When I test the model using the trained model, it looks well. Why? 2. What do the cm and kernel mean in the code? I am not very sure now. Thanks again for your nice project.

What dataset do you use for training? Is it only "dvsave-2020 _ 07 _ 23 _ 10 _ 28 _ 47. aedat4" provided by the author?Thanks.

**Comment by ZhyGao** [comment]
> 

YES

**Comment by SqLiu67** [comment]
> > 
> 
> YES

Did you try to use CLEVER-DAVIS and NFS-DAVIS provided by the author in the paper for testing? I didn't find these two DAVIS datasets on official websites or the  DAVIS datasets converted by the author.Thanks.

**Comment by ZhyGao** [comment]
> > > 
> > 
> > 
> > YES
> 
> Did you try to use CLEVER-DAVIS and NFS-DAVIS provided by the author in the paper for testing? I didn't find these two DAVIS datasets on official websites or the DAVIS datasets converted by the author.Thanks.

Same to you. I have given up for learning this project.
