### ISSUE TITLE
数据集不可用

### ISSUE THREAD

**Issue by BurtonYu** [IbrahimYang/Hybrid-neural-networks#7]
作者你好，HSN的数据集在那个清华的网址里没有找到，请问可以补充一下吗？另外请问是否可以补充一下HMN的数据集？

**Comment by IbrahimYang** [comment]
不好意思，我从清华博士毕业之后那个网盘链接自动失效了。目前我这边更新了一google drive的链接，相关数据集可以从下面这个链接中下载。https://drive.google.com/file/d/1aGj7QHiMPdQtMRUaEtVnPMhqr5YdqST6/view?usp=sharing
关于HMN其使用的都是官方的数据集，请从官方渠道下载

**Comment by BurtonYu** [comment]
非常感谢您的回复和支持，也祝您前程似锦！

**Comment by BurtonYu** [comment]
> 不好意思，我从清华博士毕业之后那个网盘链接自动失效了。目前我这边更新了一google drive的链接，相关数据集可以从下面这个链接中下载。https://drive.google.com/file/d/1aGj7QHiMPdQtMRUaEtVnPMhqr5YdqST6/view?usp=sharing 关于HMN其使用的都是官方的数据集，请从官方渠道下载

非常感谢您的回复和支持，也祝您前程似锦！
